// Minimal libwebp build config for this decode-only, single-threaded ESP32 build.
// Normally generated by autotools (./configure); we build without autotools (see platformio.ini),
// so this hand-written stand-in just leaves every optional HAVE_*/WEBP_USE_* feature undefined,
// which libwebp's headers treat as "off" throughout the decode/demux sources vendored here.
#ifndef WEBP_SRC_WEBP_CONFIG_H_
#define WEBP_SRC_WEBP_CONFIG_H_
#endif // WEBP_SRC_WEBP_CONFIG_H_
